### ISSUE TITLE
Stash Picker isn't present

### ISSUE THREAD

**Issue by mwojcik0** [gitextensions/gitextensions#12588]
### Environment

- Git Extensions 6.0.2.18262
- Build f02a06bf5366bcee241c3273951de3a132020b48
- Git 2.50.1.windows.1 (recommended: 2.51.0 or later)
- Microsoft Windows NT 10.0.26100.0
- .NET 9.0.9
- DPI 168dpi (175% scaling)
- Portable: False

### Issue description

Stash Picker isn't present and I cannot choose a correct stash.

<img width="609" height="542" alt="Image" src="https://github.com/user-attachments/assets/3301d915-f96d-42e2-b868-e9a265c22255" />

### Steps to reproduce

Create multiple stashes, and go to stash manager, the picker doesn't appear, only for w split second when extending the left side of the window.

<img width="609" height="542" alt="Image" src="https://github.com/user-attachments/assets/3301d915-f96d-42e2-b868-e9a265c22255" />

### Did this work in previous version of GitExtensions?

Yes

**Comment by mstv** [comment]
(It might be caused by the display scaling factor. Then we will need to adapt the width calculation.)

Does it appear if you move the splitter?

<img width="376" height="121" alt="Image" src="https://github.com/user-attachments/assets/e0225e49-1ec9-4a70-8bb2-23af8e016eab" />

**Comment by mwojcik0** [comment]
Yes, it appears for a split second and then disappeares.

**Comment by naviln** [comment]
> Yes, it appears for a split second and then disappeares.

Just want to chime in and say I am having the exact same issue. When I drag it wider, it appears for just a split second.

**Comment by naviln** [comment]
Just sharing my short term workaround (Windows 11):

- Right click application > Properties > Click Compatibility tab > Click Change High DPI Settings > Override high DPI scaling behaviour

- Ticked this and set the value to "System".

Now I can see the dropdown to select my stashes.
But the text looks a bit blurry and hard to read 😥

**Comment by gerhardol** [comment]
fixed in #12594

**Comment by naviln** [comment]
Hi @gerhardol,

I downloaded pre release version 6.0.3.18335 because I am desperate for this fix.
Unfortunately, the issue is still not resolved. I can't see the stash picker.

- Git Extensions 6.0.3.18335
- Build 6b4f4bf6e7d4ea8884928db8ec08d70dbb69c8a1
- Git 2.51.1.windows.1
- Microsoft Windows NT 10.0.26200.0
- .NET 9.0.10
- DPI 168dpi (175% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 8.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 10.0.0-rc.2.25502.107 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

<img width="1461" height="413" alt="Image" src="https://github.com/user-attachments/assets/fafcb6d4-f238-49dd-885f-dc78e71a72da" />

**Comment by mstv** [comment]
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/53052635/artifacts is v6.0.3 minus yet another pixel
works for me in the keyhole of my test VM at 175%

**Comment by naviln** [comment]
> https://ci.appveyor.com/project/gitextensions/gitextensions/builds/53052635/artifacts is v6.0.3 minus yet another pixel works for me in the keyhole of my test VM at 175%

@mstv I didn't quite understand what you meant, but i tried downloading the portable build that you linked, and yes this one works now. Thanks. Do you have an installer for this build?

<img width="1081" height="226" alt="Image" src="https://github.com/user-attachments/assets/da2da66a-4a6d-44f9-a499-b9450c6b0f63" />

**Comment by mstv** [comment]
(providing an) `.msi` file (from master branch did not work but from a recent PR build): https://ci.appveyor.com/project/gitextensions/gitextensions/builds/53060214/artifacts (should finish soon)

(175% in a VM in a window on a notebook with Full HD is just a keyhole.)
(Since I see subpixels, fractional scaling always looks too ugly to me. Perhaps, I will come to terms with 200% on a super-high-res display some day.)

**Comment by naviln** [comment]
> (providing an) `.msi` file (from master branch did not work but from a recent PR build): https://ci.appveyor.com/project/gitextensions/gitextensions/builds/53060214/artifacts (should finish soon)
> 
> (175% in a VM in a window on a notebook with Full HD is just a keyhole.) (Since I see subpixels, fractional scaling always looks too ugly to me. Perhaps, I will come to terms with 200% on a super-high-res display some day.)

Can't see an msi in that folder yet

**Comment by RussKie** [comment]
The build has failed

**Comment by naviln** [comment]
> The build has failed
> […](#)

OK, no problem, I'll wait for the 6.0.3 release

**Comment by mstv** [comment]
https://ci.appveyor.com/api/buildjobs/i6g24pnw9ui1dau8/artifacts/GitExtensions-x64-6.0.4.18339-3ba55d897.msi

> The build has failed

just due to intrusive tests
