### ISSUE TITLE
Filter search exception

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#2597]
I am trying to find the commit via filter by entering C642175 and application craches

**Comment by Ashod** [comment]
Reported in #2582, Fixed in PR #2583 (submitted Dec 26th).

**Comment by vzabavnov** [comment]
Hi Ashod,

I still have at:





 

Here is a stack trace:
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at GitUI.RevisionGridClasses.DvcsGraph.Graph.IsRevisionRelative(String aGuid) in c:\Dev\GitExtensions\GitUI\UserControls\RevisionGridClasses\DvcsGraph.Graph.cs:line 123

   at GitUI.RevisionGridClasses.DvcsGraph.IsRevisionRelative(String aGuid) in c:\Dev\GitExtensions\GitUI\UserControls\RevisionGridClasses\DvcsGraph.cs:line 1208

   at GitUI.RevisionGrid.SelectInitialRevision() in c:\Dev\GitExtensions\GitUI\UserControls\RevisionGrid.cs:line 1181

   at GitUI.RevisionGrid.<GitGetCommitsCommandExited>b__20(Object o) in c:\Dev\GitExtensions\GitUI\UserControls\RevisionGrid.cs:line 1149

   at GitUI.GitUIExtensions.<>c__DisplayClass18.<InvokeSync>b__17(Object s) in c:\Dev\GitExtensions\GitUI\GitUIExtensions.cs:line 330

 

With Best Regards

 <mailto:zabavnov@gmail.com> Vadim Zabavnov

**Comment by Ashod** [comment]
@vzabavnov My PR (which fixes the issue) hasn't been merged yet. I was pointing out that there is duplicate effort, not that it's already fixed in master.

**Comment by vzabavnov** [comment]
Thank you, Ashod. For now I will roll back to 2.48.0 version. 

 

 

With Best Regards

 <mailto:zabavnov@gmail.com> Vadim Zabavnov
