### ISSUE TITLE
GitExtensions toolbar keeps re-enabling itself

### ISSUE THREAD

**Issue by mmoore99** [gitextensions/gitextensions#2619]
In Visual Studio 2013, if the Git Extensions toolbar is disabled, it gets re-enabled when Visual Studio restarts.  

Is there any way to stop this behavior?

**Comment by hypergod** [comment]
If the Git Extension toolbar is disabled then my Visual Studio 2013 will crashes on start.
Message: A new guard page for the stack cannot be created.

Workaround:
To recover Visual Studio I have to set the key
HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0\AutomationOptions\LoadAddIns
to 0. Then I can enable the Git Extension toolbar again.

**Comment by tophf** [comment]
Another issue with the toolbar: it doesn't remember it's position and always creates a new row for itself.

**Comment by KindDragon** [comment]
This should be fixed in 2.48.04

**Comment by shmup** [comment]
It isn't fixed. I can open Visual Studio, right click and disable the GitExtensions toolbar, close Visual Studio, and it's enabled again upon reopening.
