### ISSUE TITLE
Issues with staging numerous files

### ISSUE THREAD

**Issue by Esteban-Rocha** [gitextensions/gitextensions#2677]
Hello, I discover a problem, I don't know if I'm the only one with this issue.

On a new wordpress project I'm working on, The very first commit of the wordpress structure witch was a couple of hundreds files but small size (no more than 8 MB) GitExt could not stage the files, it just crashed every single time I try it.

When I tested adding the files to the staging area from git bash it ran smoothly, so I know it was not an error from my part, besides i had used the .gitignore aimed to wordpress to reduce many unnecessary files and folders. Plus I had done the same thing many times on the past on GitExt and worked... Update issue maybe?

I did not receive any error message, the application just hanged when staging the 800+ files, but as I say before on git bash I do it smoothly and it took me less than 10 sec. to do so, so as it hanged I waited for almost 20 minutes with no response whatsoever from GitExt just to finally kill it with my task manager after several minutes. I did this at least 4 times, none of them worked.

I don't think this may be an issue of my environment, as I say before it worked cool just before the update.

**Comment by KindDragon** [comment]
This bug should be fixed in 2.48.04

**Comment by remcoros** [comment]
I just tried staging ~ 750 files and it still hangs for around 30 sec - 1 minute. While using 'git add .' is almost instant.

version 2.48.05

**Comment by KindDragon** [comment]
`git add .` show any warnings?

**Comment by remcoros** [comment]
nope, it goes as normal. 

I'll get the source and check a profiler session as soon as I get around to it
