### ISSUE TITLE
Problems with putty to clone from ssh:// with port.

### ISSUE THREAD

**Issue by SetoKaiba** [gitextensions/gitextensions#2681]
Problems will occur with putty client as SSH for git extensions.
When the host isn't a known host, it will prompt for trust the host key.
And then I click yes, it will try to trust the host key. It will report "FATAL ERROR: Network error: Connection refused".

2015-03-02 20:09:02 [INFO ] creating ssh session from /127.0.0.1:11695
2015-03-02 20:09:02 [WARN ] Exception caught
java.io.IOException: The specified network name is no longer available.

	at sun.nio.ch.Iocp.translateErrorToIOException(Unknown Source)
	at sun.nio.ch.Iocp.access$700(Unknown Source)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2015-03-02 20:09:02 [INFO ] closed ssh session from /127.0.0.1:11695

It will connect and disconnect immediately. Then the network error will report.

And if I use OpenSSH as SSH, it works correctly. If I use PUTTY.exe to connect to GitBlit/GitBucket, it will prompt the cache host key as well. But it  won't disconnect. And if I cache host key with PUTTY.exe, Git Extensions works correctly. That means it's the problem of the cache host key logic in Git Extensions.

**Comment by SetoKaiba** [comment]
It's the bug of FormRemoteProcess.cs. Before call AskForCacheHostkey should "remoteUrl = GitCommandHelpers.GetPlinkCompatibleUrl(remoteUrl);" first. Because putty is with problem with url starts with "ssh://". Please fix this in 2.48.04. I wait for it for long because of the freeze of committing stderr problem. And also you can add "echo y |" to plink command to automatically cache the host key.

**Comment by SetoKaiba** [comment]
Is there any night build or something similar? Some bugs is blocking level. And it's not fixed in the released version. But I can't compile the project myself.

**Comment by SetoKaiba** [comment]
And also even the GitCommandHelpers.GetPlinkCompatibleUrl is with bug when the ssh:// with specified port.
ssh://test@localhost:29418/test.git
should be formatted as -P 29418 test@localhost:test.git.
Now is test@localhost:29418/test.git which is unable to be recognized by Putty.

**Comment by SetoKaiba** [comment]
GitCommandHelpers.GetPlinkCompatibleUrl should be as below.

```C#
        public static string GetPlinkCompatibleUrl(string inputUrl)
        {
            // We don't need putty for http:// links and git@... urls are already usable.
            // But ssh:// urls can cause problems
            if (!inputUrl.StartsWith("ssh") || !Uri.IsWellFormedUriString(inputUrl, UriKind.Absolute))
                return inputUrl;

            // Turn ssh://user@host/path into user@host:path, which works better
            Uri uri = new Uri(inputUrl, UriKind.Absolute);
            string fixedUrl = "";

            if (!uri.IsDefaultPort)
                fixedUrl += "-P " + uri.Port + " ";

            if (!String.IsNullOrEmpty(uri.UserInfo))
                fixedUrl += uri.UserInfo + "@";
            fixedUrl += uri.Host;
            fixedUrl += ":" + uri.LocalPath.Substring(1);

            return fixedUrl;
        }
```

**Comment by SetoKaiba** [comment]
FormRemoteProcess.HandleOnExit method

```C#
                    if (AskForCacheHostkey(this, Module, remoteUrl))
                    {
                        Retry();
                        return true;
                    }
```

should add before

```C#
remoteUrl = GitCommandHelpers.GetPlinkCompatibleUrl(remoteUrl);
```

**Comment by SetoKaiba** [comment]
Could you please give me a compiled GitUI.dll after fix it? I can't use ssh://  with specified port with this bug. Thanks.

**Comment by SetoKaiba** [comment]
Faint. GitCommandHelpers.GetPlinkCompatibleUrl even doesn't exist yet in the 2.48 branch.

**Comment by SetoKaiba** [comment]
I forked the repository and fixed the bug. But it's fixed in master branch. The 2.48 branch is even without GetPlinkCompatibleUrl. And I tested ok. And I update the unit test as well.
My repository is https://github.com/SetoKaiba/gitextensions0

**Comment by SetoKaiba** [comment]
No one answers? I think maybe a cherry pick for plink fix from Noguai would be ok.

**Comment by SetoKaiba** [comment]
Why no reply for my issue and pull request?

**Comment by KindDragon** [comment]
Sorry. I was very busy. I will review your PR

**Comment by KindDragon** [comment]
fixed by #2686

**Comment by infabo** [comment]
Seems to be still an issue in 2.48.05. Can't pull/push from/to ssh://user@host/foo.git URLs. Always tries to use "ssh://user" as the login-user for putty (instead of just "user").
