### ISSUE TITLE
"Failed to load plugin Stash.dll" on new build

### ISSUE THREAD

**Issue by kaotik4266** [gitextensions/gitextensions#2942]
With a fresh clone from master, I am able to build without any errors but receive the following popup after opening the application:

![popup](https://cloud.githubusercontent.com/assets/4526480/9780342/eefc17c6-57ca-11e5-9500-8954c65ed998.png)

Additonally, when attempting to build the installers I receive the following error:

```
C:\GitExtensions\Setup\Product.wxs(238): error LGHT0103: The system cannot find
 the file '..\GitExtensions\bin\Release\Newtonsoft.Json.dll'. [C:\GitExtensions
\Setup\Setup.wixproj]
```

**Comment by linquize** [comment]
See #2937

**Comment by kaotik4266** [comment]
Forgot to update this. That pull request fixes the issue for installers but causes it to occur for regular builds.

**Comment by Radrik5** [comment]
@kaotik4266 what do you mean by "regular builds"? I just successfully built Debug configuration in VS 2013 after cleaning working copy. Release build fails because of invalid paths to KDiff3, Git, and other dependencies not related to Newtonsoft.Json (only Newtonsoft.Json was fixed in that PR).

**Comment by Radrik5** [comment]
Release build in VS 2013 successfully finishes after running `BuildInstallers.VS2013.cmd` at least once.

**Comment by kaotik4266** [comment]
After applying the pull request, Debug and Release builds both finish successfully, however Debug configuration displays the popup from my initial post when the application is run:
![screenshot](https://cloud.githubusercontent.com/assets/4526480/10151965/96982ac8-6690-11e5-881f-53c525db61b5.png)

The following appears in the debug output when `Ok` is clicked:
```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

**Comment by UncleVasya** [comment]
Sometimes it happens top me, when I switching between GitExt revisions a lot. 
Try to delete bin/Release/ and bin/Debug/ folders, it always helps me (cleaning solution won't help).

**Comment by cromulus80** [comment]
I'm also having this issue after upgrading to a newer release of GitExtensions.  I upgraded from one released version (sorry, don't recall the version number) to another.  I have never built GitExtensions from source.

![image](https://cloud.githubusercontent.com/assets/22918246/19488683/9673e5ce-952d-11e6-9c28-fa4dd59e3bb7.png)


GitExtensions2.48.05, Git 2.9.0.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by KindDragon** [comment]
Try remove it and install it again with all features enabled.

**Comment by EbenZhang** [comment]
fixed by #3101

**Comment by timotei** [comment]
I am on 2.49.03 and this still happens, though the newtonsoft.json library version is 6.0.0.0 in the error message

**Comment by KindDragon** [comment]
Please try to remove GitExt completely and install it again
