### ISSUE TITLE
Consider disabling status bar of ConEmu

### ISSUE THREAD

**Issue by karyon** [gitextensions/gitextensions#3172]
Given this screenshot
![b0cada1c-ebc4-11e5-91f0-38dfead54805](https://cloud.githubusercontent.com/assets/1891915/14583742/6c94b096-042b-11e6-88a8-213541876bee.png)

there is quite a bunch of numbers in that status bar and for each single one i have no clue what it should mean. additionally, it says "git" to tell us we're running git. also, the status bar protruding to the right below the scroll bar looks bad in my opinion. the only helpful part is "ssh.exe" but i don't think it's that important.

:)

**Comment by KindDragon** [comment]
@hypersw What do you think?

**Comment by phillijw** [comment]
I agree but unless it's causing an actual issue, I'd think we can make this change in a future release. I'm ready for 2.49 to be released

**Comment by KindDragon** [comment]
At least we should try to investigate. Perhaps it is easy to do

**Comment by phillijw** [comment]
Based on the PR, it does not appear to be something trivial since that one doesn't seem to work consistently. There are some underlying settings that are affecting the result which will need to be worked out.

**Comment by jbialobr** [comment]
Done in 4e5c21b21124b03587f4d613d73afe5b4e519385

**Comment by phillijw** [comment]
@jbialobr  I wonder if something is polluted on your machine because my 2.49RC1 installation still shows the status bar

**Comment by miparnisari** [comment]
Hey guys, I just pulled 2.49RC1 and I cannot pull or push anything because I get a prompt to store a key in the cache but when I press "y" nothing happens. Any ideas?

![image](https://cloud.githubusercontent.com/assets/5374887/19324364/a0342578-9097-11e6-9380-7d88399bc715.png)

**Comment by jbialobr** [comment]
@phillijw See the commit log - the v2.49RC1 does not contain my commit.

**Comment by phillijw** [comment]
@miparnisari As a temporary workaround I would suggest just storing the key by using the git bash terminal. Just do a push or pull command from there instead.

**Comment by KindDragon** [comment]
@miparnisari Please create issue for that

**Comment by miparnisari** [comment]
@KindDragon someone else did it for me :) https://github.com/gitextensions/gitextensions/issues/3356 and also https://github.com/Maximus5/ConEmu/issues/913
