### ISSUE TITLE
Can't Paste Into Commit 

### ISSUE THREAD

**Issue by mjk70** [gitextensions/gitextensions#3408]
--- GitExtensions2.48.05, Git 2.10.1.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

This is so critical for me... I paste EVERYTHING (comments from bug reports, notepad++ text, ec)  into the commit message box that I'm considering reverting back to the ancient version I was using before just to get this feature back.

![image](https://cloud.githubusercontent.com/assets/11297696/20184430/a3030e6c-a736-11e6-8167-f482fa1df529.png)

**Comment by KindDragon** [comment]
> GitExtensions2.48.05

We released version 2.49. Please update GitExt

**Comment by nul800sebastiaan** [comment]
I still have this problem sometimes in 2.49 and can't find a pattern as to when this stops working. However, pasting with SHIFT+INS always works so I'm using that.

**Comment by mjk70** [comment]
Thanks Sebastiaan!! SHIFT+INS works for me where both standard right click
context menu paste AND ctrl-V  STILL do not...  huge time saver.

**Comment by timramone** [comment]
Still have a problem even with 2.49 :(
Thanks for SHIFT+INS workaround btw

**Comment by RussKie** [comment]
Is this still a problem in the current version?

**Comment by timramone** [comment]
It seems it's fine now
