### ISSUE TITLE
GitEx does not remember splitter position

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#4058]
**Do you want to request a *feature* or report a *bug*?**
I would like to report about a **bug**.

**What is the current behavior?**
GitEx resets splitter position after toggling it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* open repository
* move splitter to some position
* press "Toggle split view layout" button (above revision grid, at top right corner) to hide commit info and once again to show it back
* commit info panel is in center now, it does not remember its old position.

**What is the expected behavior?**
It would be nice to remember the old position of the splitter.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.13.0.windows.1
- OS version: Windows 7 x64.

**Did this work in previous version of GitExtensions (which)?**
I don't think so.

**Comment by pravic** [comment]
Also GitEx does not remember splitter position in Stash viewer dialog.

**Comment by pravic** [comment]
It does not remember its position even for the same repositories. Just resets from time to time (which is not a problem itself if we would have a proper default size).

![splitter](https://user-images.githubusercontent.com/724639/33655661-c2c79114-da84-11e7-99cf-6f7ae7fc1edc.png)

**Comment by RussKie** [comment]
This is fixed in #3681

**Comment by RussKie** [comment]
Duplicate of #3966

**Comment by jbialobr** [comment]
@RussKie This is a separate issue and it is not fixed. See the repro steps.

**Comment by RussKie** [comment]
Apologies

**Comment by pravic** [comment]
Exists in 2.51 so no, it is not a duplicate of #3966.

**Comment by RussKie** [comment]
In my opinion it is not a bug, it is by design.

**Comment by pravic** [comment]
In this case I don't have anything against it. @jbialobr?

**Comment by jbialobr** [comment]
To me it looks more like misfortune implementation unless I misunderstand the idea of toggle split view layout. In my opinion it should be for quick hiding the bottom panel to be able see as much as possible of the revision graph view, but it should not be persisted for it is a temporary change to the layout.
I created a PR #4294 that fixes this issue.
