### ISSUE TITLE
Crash during copy to clipboard

### ISSUE THREAD

**Issue by masko23** [gitextensions/gitextensions#4542]
Git Extensions version: 2.50.02

Issue description:
When trying to use copy to clipboard feature, Git Extensions crash and throw the exception window seen on attached screenshot.
I suspect that it has some trouble with Beyond Compare 4 Clipboard compare feature. See steps to reproduce:
Testcase 0:
1. Beyond Compare Clipboard compare feature already runs
2. Start Git Extensions
3. Use Copy to clipboard feature from context menu on a branch (on any data: commit hash, branch name etc.)
Result: crash, but string is copied to clipboard

Testcase 1:
1. Beyond Compare Clipboard compare feature already runs
2. Start Git Extensions
3. Close BC Clipboard compare
4. Restart Git Extensions
5. Use Copy to clipboard feature from context menu on a branch (on any data: commit hash, branch name etc.)
Result: crash, but string is copied to clipboard

Testcase 2:
1. Beyond Compare Clipboard compare feature already runs
2. Start Git Extensions
3. Close BC Clipboard compare
4. Use Copy to clipboard feature from context menu on a branch (on any data: commit hash, branch name etc.)
Result: no crash, string is copied to clipboard

Testcase 3:
1. Beyond Compare Clipboard compare feature is not running
2. Start Git Extensions
3. Use Copy to clipboard feature from context menu on a branch (on any data: commit hash, branch name etc.)
Result: no crash, string is copied to clipboard

I haven't looked at Git Extensions source code since I'm only a user of it yet but perhaps you have some idea about this. 
I saw that there were already issues related to the clipboard feature.

![image](https://user-images.githubusercontent.com/10179556/36780028-21ff433c-1c72-11e8-81a7-92f7b0c15b14.png)

**Comment by gerhardol** [comment]
I cannot reproduce with bc4

**Comment by masko23** [comment]
I've cloned the GitExtensions repository and succesfully runned the program in debug mode. It seems every Clipboard.SetText method throws System.Runtime.InteropServices.ExternalException when I try to copy something. It seems to me that Beyond Compare's clipboard compare feature somehow blocks the clipboard but still the SetText method successfully set the clipboard but still throws exception. I continue my investigation if I have time for it.

**Comment by masko23** [comment]
I've created a new class in GitUI with a static method that does this handling:
```
    public class ClipboardHelper
    {
        public static bool SetText(string text)
        {
            var Success = false;
            try
            {
                Clipboard.SetText(text);
                Success = true;
            }
            catch (System.Runtime.InteropServices.ExternalException)
            {
                Success = false;
            }

            return Success;
        }
    }
```

Now it works but someone who is more experienced with clipboard operations check if this solution worth a pull request since I'm not part of the developers for this software.

**Comment by AntonD-mobilmir** [comment]
I have same problem, but it's unstable – it occurs more often when I copy from gitextensions commit dialog diff window with TeamViewer connection open in background, yet still not always.

No other program crashes with same environment conditions, but I've seen Ctrl+C doing nothing (have to retry 2-3 times before clipboard receives the selected fragment).
 
I'm not using GitExtensions very often, but I'm sure I've seen this crash with ver 2.51. For some time (about a year), I've sent reports each crash, but recently stopped doing it.

**Comment by RussKie** [comment]
Slightly OT. I don't know if the crash reports are actually sent anywhere.
A zip is created, I've seen it, but no idea what happens next.
Something to sort out for sure.

**Comment by AntonD-mobilmir** [comment]
GitExtensions.exe [2.51.02], same problem continues
![image](https://user-images.githubusercontent.com/7845465/41156187-8430531a-6b29-11e8-9c92-183a10524ffc.png)

![image](https://user-images.githubusercontent.com/7845465/41156219-9f2e38a8-6b29-11e8-8320-8bdfa0761c56.png)


Stack Trace
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

**Comment by ioanb7** [comment]
+1, version 2.51.05

**Comment by RussKie** [comment]
What are your OS, .NET version, anything else that may help to determine a
root cause?

**Comment by AntonD-mobilmir** [comment]
my guess is that it's about clipboard lock: like if some program writes clipboard twice in short period, another one which monitors clipboard (TeamViewer in my case) may lock it temporarly to read consistently, and then it's race condition (if first program is fast enough, it will write before second program locks; or, if it's too slow, second program will lock, read and unlock before first program does second write).

**Comment by ioanb7** [comment]
> my guess is that it's about clipboard lock: like if some program writes clipboard twice in short period, another one which monitors clipboard may lock it temporarly to read consistently, then it's race condition (if first program is fast enough, it will write before second program locks; or, if it's too slow, second program will lock, read and unlock before first program does second write; if first program will try to write while second program has clipboard locked, it will fail).
> 
> And TeamViewer may increase probablility of this effect because it seems it locks clipboard for whole time of clipboard transfer over the network, which may take seconds in case of slow networks or lagging TeamViewer servers.

That makes a lot of sense as I know my clipboards are being monitored by the company I work for. 

@RussKie Windows 10 enterprise, latest version of .net

What happens: I go into the window where I can commit my files, select some text, and then it crashes (like in the picture above) but the text does get copied - I can paste it afterwards.

**Comment by RussKie** [comment]
I think the hypothesis is sound, [this SO thread](https://stackoverflow.com/q/5707990/2338036) runs along the same lines.

I think we need to update all our clipboard-related calls to use [xxx](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard.setdataobject?view=netframework-4.7.2#System_Windows_Forms_Clipboard_SetDataObject_System_Object_System_Boolean_System_Int32_System_Int32_). 
And for the good measure, abstract it too.

**Comment by AntonD-mobilmir** [comment]
Not sure if it should be fixed in GitExtensions.exe [3.00.00.03-RC2], but it happens still:

![image](https://user-images.githubusercontent.com/7845465/48561117-592a0d00-e900-11e8-911c-7f5fd6b4dce0.png)

**Comment by AntonD-mobilmir** [comment]
maybe this will somewhat help.
* Never crashes when copying here: ![image](https://user-images.githubusercontent.com/7845465/48561582-4d8b1600-e901-11e8-8b2b-a05fc111f136.png)
* Fairly reliably crashes when copying here: 
![image](https://user-images.githubusercontent.com/7845465/48561627-65fb3080-e901-11e8-8281-ba30b24aac0b.png)

**Comment by drewnoakes** [comment]
@AntonD-mobilmir it should be fixed when https://github.com/gitextensions/gitextensions/pull/5746 is merged.

**Comment by mwerle** [comment]
Still happens with current GitExtensions v3.0.2.5232.

Crash:
* Highlight (part of) the commit hash.
* Press Ctrl-C
* **BOOM**

Interestingly enough if using Ctrl-Insert instead of Ctrl-C, it works fine.

**Comment by gerhardol** [comment]
@mwerle
Open a new issue

**Comment by mwerle** [comment]
Huh, bizarre, on my home PC it's working even with Ctrl-C. Will have to compare what's different between my work & home PCs (I know GitExtensions on both is at the most recent version). Will raise a new issue tomorrow.

**Comment by RussKie** [comment]
I couldn't repro the issue.

Do you have some app perhaps that monitors the clipboard?

**Comment by mwerle** [comment]
> I couldn't repro the issue.
> 
> Do you have some app perhaps that monitors the clipboard?
It's possible (it's a Company-managed PC so there might be some security stuff snooping around), although copying the same data from other apps to the clipboard does not result in a crash. 

I'll try to find some time and debug it; looks like it's solved for most people (and even for my other PCs) so it must be something on this PC that's causing hassles. And I've got a workaround anyway : use Ctrl-Insert instead.
