### ISSUE TITLE
Text entering over the top of commits tree

### ISSUE THREAD

**Issue by DoctorChaOs96** [gitextensions/gitextensions#6419]
## Current behaviour
Text displays over the top of commits tree

## Expected behaviour
User shouldn't have possibility to enter text or text should not be displayed.

## Steps to reproduce

1. Click on higher commit on commits tree
![1](https://user-images.githubusercontent.com/26484855/55227035-19185680-521f-11e9-9000-ffbce7650e00.png)

2. Start enter text
![2](https://user-images.githubusercontent.com/26484855/55227053-246b8200-521f-11e9-9124-d20c84df0108.png)

3. Then you can see text over the top of commits tree

## Screenshots

![1](https://user-images.githubusercontent.com/26484855/55227062-2d5c5380-521f-11e9-8740-b80b58ced630.png)
![2](https://user-images.githubusercontent.com/26484855/55227063-2df4ea00-521f-11e9-9eb7-8ff48378bc29.png)

## Did this work in previous version of GitExtensions

I don't now

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Could you modify the issue to include the screenshots directly into the issue (you just have to paste into the message if the screenshot is in your clipboard).

That way the issue will be easier to read to everyone without having to click on every links...

**Comment by DoctorChaOs96** [comment]
Done

**Comment by pmiossec** [comment]
Now that I understand the issue (seeing the screenshots 😉 ), I can tell you that you missed the point 😢 and that it's a feature.

That's the "quick search" feature. The text you type is searched in the commit messages and the matching commit is selected.

Perhaps we could make that clearer by add the text "Searching for:" before...

**Comment by pmiossec** [comment]
You could find the explaination in the menu `Navigate` => `Quick Search`.

**Comment by gerhardol** [comment]
> Perhaps we could make that clearer by add the text "Searching for:" before...

Seem reasonable
