### ISSUE TITLE
Ever since version 3.2.1, setup fails with "This application requires PowerShell"

### ISSUE THREAD

**Issue by DaveVdE** [gitextensions/gitextensions#7524]
## Current behaviour

Currently have 3.1.1 installed.

I tried installing 3.2.1 after getting the in-app update notification, but that failed with the following error: "This application requires Powershell". I figured this would be caught by someone so I just waited it out, but today I tried installing 3.3 (GitExtensions-3.3.0.7719.msi) and it gave me the same error. 

I've scanned the open and closed issues, and checked my local environment. Indeed, I'm on a computer in an organisation that has some form of corporate control (or more than one), but in Powershell "$ExecutionContext.SessionState.LanguageMode" evaluates to "FullLanguage".

## Expected behaviour

I would expect to be able to upgrade to the latest without a hitch.

## Steps to reproduce

- Double-click the downloaded setup package.
- Choose "Install for all users"
- Keep default install location (C:\Program Files (x86)\GitExtensions\)
- Keep component selection as is
- Choose "OpenSSH" (It's how my current setup is configured)
- Keep telemetry on (tried without too, no difference)
- Click "Install"

## Screenshots

![image](https://user-images.githubusercontent.com/650760/71063567-399d8d80-216d-11ea-90ee-87b05aeb6eb4.png)

## Did this work in previous version of GitExtensions

Current installed version worked, couldn't get newer versions (3.2.1 or newer) to install.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

## Diagnostics

Please let me know what I can do to assist in investigating the problem.

**Comment by RussKie** [comment]
Please try downloading from GitHub and installing v3.3, and let us know
if it works (or doesn't).

**Comment by DaveVdE** [comment]
I downloaded GitExtensions-3.3.0.7719.msi through GitHub, and tried the same but I have the same behavior.

**Comment by RussKie** [comment]
Can you share a log?

**Comment by DaveVdE** [comment]
How do I produce a log?

**Comment by DaveVdE** [comment]
I produced a log using the following command line: 

`msiexec /i "C:\Users\xxxx\Downloads\GitExtensions-3.3.0.7719.msi" /L*V "C:\log\install.log"`

Without sharing the entire log file, I think I found the offending part here:

```
Action 13:01:52: LaunchConditions. Evaluating launch conditions
Action start 13:01:52: LaunchConditions.
This application requires Windows PowerShell.
MSI (s) (E8:1C) [13:01:55:396]: Note: 1: 2205 2:  3: Error 
MSI (s) (E8:1C) [13:01:55:396]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (E8:1C) [13:01:55:396]: Product: Git Extensions 3.3.0.7719 -- This application requires Windows PowerShell.

Action ended 13:01:55: LaunchConditions. Return value 3.
Action ended 13:01:55: INSTALL. Return value 3.
```

How can I find in the log where it comes to that conclusion?

**Comment by DaveVdE** [comment]
Just for shits 'n giggles, I tried executing the same in a command window run as Administrator, and it seems to work that way.

This could very well be environmental. In that case, I thank you for the assistance and will close this issue at once.

**Comment by RussKie** [comment]
Hmm... could be that your local gpo prohibits executing PS scripts 🤔

**Comment by simplyaboutcode** [comment]
Any new info about that? Have similar problem :(

**Comment by DaveVdE** [comment]
It was a problem with the machine. Probably some enterprise-level global policy thing.

It worked for me if I started the installer explicitly as Administrator.

**Comment by pmiossec** [comment]
I think that will be fixed by #7442 once next version of gitextensions will be released...

**Comment by RussKie** [comment]
That was fixed in 3.3. Updated to the latest version.

**Comment by MikeSchurman** [comment]
![image](https://user-images.githubusercontent.com/7268923/80803061-8cf60280-8b87-11ea-8947-08bfe98e48de.png)
This still happens for me, I have powershell installed.

**Comment by simplyaboutcode** [comment]
@RussKie I couldnt update because this error occured during update. Didnt try remove/add program thougt.

@MikeSchurman you’re great !! That worked for me also :)

**Comment by RussKie** [comment]
@simplyaboutcode we need logs to provide any meaningful feedback. Changes are it is locked by your corporate group policy (if it is a work computer).

**Comment by NerdFan** [comment]
![image](https://user-images.githubusercontent.com/21181182/110079060-48338d00-7d91-11eb-9e89-0807e23bcb8b.png)

**Comment by ffonz** [comment]
Had the same problem, even with 4.0.0. I solved it to open a command prompt with elevated rights, but this is not a neat solution. Maybe better if the installer asks for elevated rights. But the best solution would be if Git Extensions could be installed without administrative rights.

**Comment by ffonz** [comment]
[install.log](https://github.com/gitextensions/gitextensions/files/9991580/install.log)

I hope this log helps solving the issue.

**Comment by kevilay** [comment]
I had this same issue on v7.0.3. To resolve run the installer in a cmd prompt as admin.

1. Windows Key --> Type Command Prompt --> Right click --> Run As Admin
2. Find the path of your downloads folder ("C:\Users\Username\Downloads"). Generally this is it.
3. In command prompt type cd C:\Users\Username\Downloads to switch to the directory of the downloaded file
4. Type ecatcher.msi --> This will run it as admin in the cmd prompt

**Comment by DaveVdE** [comment]
> I had this same issue on v7.0.3. To resolve run the installer in a cmd prompt as admin.
> 
> 1. Windows Key --> Type Command Prompt --> Right click --> Run As Admin
> 2. Find the path of your downloads folder ("C:\Users\Username\Downloads"). Generally this is it.
> 3. In command prompt type cd C:\Users\Username\Downloads to switch to the directory of the downloaded file
> 4. Type ecatcher.msi --> This will run it as admin in the cmd prompt

We're at v7 now?

**Comment by SAPHemlock** [comment]
> Had the same problem, even with 4.0.0. I solved it by opening a command prompt with elevated rights and install the .msi from there, but this is not a neat solution. Maybe better if the installer asks for elevated rights. But the best solution would be if Git Extensions could be installed without administrative rights.

This solution works today even in 2026 for the recent updates where we are getting missing powershell error in windows 11. Thanks
