### ISSUE TITLE
Allow interacting with main window while secondary window is open

### ISSUE THREAD

**Issue by Holo-Viktor** [gitextensions/gitextensions#8885]
Currently, you cannot interact with the main window while the commit window is open, but often (especially with submodules) I need to go back and forth between submodules or scroll in the git history while composing a commit.
It would be convenient to still be able to interact with the main window while having the commit window open, or any sub window for that matter.

**Comment by Holo-Viktor** [comment]
To prevent getting confused as to which submodule the commit window is committing to it would be helpful to introduce some kind of color coding which associates the commit window to the submodule it is committing to

**Comment by vbjay** [comment]
That's by design. Close the commit window. Do whatever you need to do. Then
open commit window again.

**Comment by Holo-Viktor** [comment]
I understand that this is the current design, this is a feature request

**Comment by vbjay** [comment]
If submodule changes, right click it in the commit window.

**Comment by pmiossec** [comment]
> It would be convenient to still be able to interact with the main window while having the commit window open, or any sub window for that matter.

Workaround: open a new GitExtensions window.

There is also a work in progress #7825 by @gerhardol for next version to be able to stage and unstage files from the file tree of main window (i.e Browse form) that will theoretically obliged just to open the commit window only to add the commit message (or for other advanced feature)

**Comment by Holo-Viktor** [comment]
I don't want to open up new gitextensions instances to look something up.
Windows inconveniently places them randomly on my workspace (which consists of 4 screens), it would greatly increase the user experience if I could just double-click on a submodule in the repo tree

**Comment by vbjay** [comment]
Right click the submodule change in commit window. Look at the context menu
options.

**Comment by Holo-Viktor** [comment]
@vbjay yes, which context menu item are you suggesting here? "Open with Git Extensions", "Commit submodule changes", "View history"?
They all open a *new* window and "Commit submodule changes" even blocks the previous commit window.
Also, it seems you have misunderstood my situation.
I have my root repo open in gitextensions, it has multiple submodules of which two are a server and a client.
I double-click on the server submodule (now I'm working within this submodule), I open the commit window and while I'm composing the commit message I want to refer to something in the client submodule which is related to this commit, it may be a previous commit message, a file change, the file tree structure, a branch name, the commit history tree etc. all of this information is already accessible in the main window which is already open (e.g side by side to the commit window).
I shouldn't need to nor do I want to open a separate gitextensions instance because I might get them confused throughout the day or reopen the same repo windows over and over, not to mention the need to position them again and again to move them out of the way.
I also don't want a trimmed down window like what the "View history" context menu item provides to only do part of what I might potentially want.
Just let use the main window and have a unified workflow for navigating my repository structure, it would make the usage of your app a lot easier.

**Comment by vbjay** [comment]
The point of the modal dialog is that it allows us to know when you are
done with the commit work and to update ui and keep things in sync. So you
can either close commit dialog and do as you desire, or pop the submodule
ui in another instance. I would raise a different issue on where the new
process window shows.

**Comment by drewnoakes** [comment]
I'm also not a fan of modal windows. Knowing a bit about how GE is implemented, it seems like forcing a sub-optimal experience on the user to make certain implementation concerns easier. There are other ways to know when a commit is made, for example. The modal commit form has other usability issues too, such as the inability to dock to sides/quadrants of the desktop.

**Comment by gerhardol** [comment]
It seems like you want to commit to the submodule repo while still having the main repo open.
This will likely not be supported like that, a GE "browse" window handles one repo with one checked out version.
In next version you do not have to open the submodule to commit (the commit form is still modal though).

![image](https://user-images.githubusercontent.com/6248932/109079377-27b76300-76ff-11eb-8087-f5e8e59c73e6.png)

The Commit popup will likely stay modal, it is hard to change that. The way forward that I see is to use the artificial commits.
Since 3.0 or so you can stage/unstage files in the artificial commits.
In next version you can also stage/unstage specific lines (comparing with any version) as mentioned.

The primary missing part is to modify the commit message and to actually commit.
That should be done in the CommitInfo tab or panel (depending on how you configure GE).

But for your specific use case you will have to use two instances.

**Comment by RussKie** [comment]
You can also open "Commit" dialog from Windows Explorer, this way I think you should be able to achieve the desired.

**Comment by RussKie** [comment]
Given the current behaviour existed for many years, a lot of users have got used to it. 
Making the "Commit" window modeless will likely cause a lot of confusion, and will require a significant effort, starting with understanding all existing and possible the UX and workflows, and answering questions like: "a user has opened the Commit dialog, and then switched to another repo/switched to another commit/created branch/deleted branch/etc/etc/etc. What is the expected UX in such situation?".

If you feel passionate about this, you're welcome to champion the feature and draft a proposal, which considers all scenarios, discusses pros and cons.

**Comment by pmiossec** [comment]
> 
>
> Given the current behaviour existed for many years, a lot of users have got used to it.
> Making the "Commit" window modeless will likely cause a lot of confusion, and will require a significant effort, starting with understanding all existing and possible the UX and workflows, and answering questions like: "a user has opened the Commit dialog, and then switched to another repo/switched to another commit/created branch/deleted branch/etc/etc/etc. What is the expected UX in such situation?".
> 
> If you feel passionate about this, you're welcome to champion the feature and draft a proposal, which considers all scenarios, discusses pros and cons.

This comment perfectly sum up the whole problem. It's easy to find one workflow that will be better if commit form is not modal but to ensure everything is handled well if we go this way.

I also think that having a not modal commit form will be better but I  can't even think of all the impacts that could have (and so I can't imagine that someone that is not a developer on the project could have the answer).

If someone really want to do this change, he has to do it in his own build and use it during days to see what all should be fixed and if it worth it...

**Comment by ivangrek** [comment]
I think we need some kind of mechanism to invert the window dependency. So that we could send a command/query and listen for an event after the change. Any part would subscribe to this event.

**Comment by RussKie** [comment]
> I think we need some kind of mechanism to invert the window dependency. So that we could send a command/query and listen for an event after the change. Any part would subscribe to this event.

https://github.com/gitextensions/gitextensions/issues/6014#issuecomment-450614606

**Comment by RussKie** [comment]
I'm going to close this as the Core team is aware of the issue, but no immediate work is planned due to the reasons explained above.
