### ISSUE TITLE
Hang when select big file in diff tab

### ISSUE THREAD

**Issue by dimmduh** [gitextensions/gitextensions#9969]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

Git project on SSD

### Issue description

When select commit with big file  (more than 50 mb) in diff tab 
gitextention will hang for seconds

https://www.youtube.com/watch?v=NOvPlfgshx0

### Steps to reproduce

Commit with big file (more than 50 mb).
Than select this commit in commits history.

### Did this work in previous version of GitExtensions?

the always has to been.

**Comment by pmiossec** [comment]
Fixed by #9908 ? Could you test the development version to confirm?

**Comment by dimmduh** [comment]
Tested 4.0.0.13754
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts
Issue still exists.

**Comment by dimmduh** [comment]
Fixed dirty by work for us
https://github.com/Volday/gitextensions/commit/2503701bffa537dba507c3bb9dfc07490d6b8495

**Comment by gerhardol** [comment]
Git Command Log for this?
What type of changes in the file?

#9908 will not speed up the handling but you should be able to select another file.
